-- HyperRoute Intelligence
-- Activity logs / audit history foundation.

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  company_id uuid references public.companies(id) on delete set null,
  actor_user_id uuid,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  description text not null,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.activity_logs enable row level security;

drop policy if exists "activity_logs_read" on public.activity_logs;
drop policy if exists "activity_logs_insert" on public.activity_logs;
drop policy if exists "activity_logs_platform_delete" on public.activity_logs;

create policy "activity_logs_read"
on public.activity_logs
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_has_company_access(company_id)
);

create policy "activity_logs_insert"
on public.activity_logs
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_has_company_access(company_id)
);

create policy "activity_logs_platform_delete"
on public.activity_logs
for delete
to authenticated
using (
  public.user_is_platform_admin()
);

create index if not exists idx_activity_logs_company_id on public.activity_logs(company_id);
create index if not exists idx_activity_logs_created_at on public.activity_logs(created_at desc);
create index if not exists idx_activity_logs_entity on public.activity_logs(entity_type, entity_id);
create index if not exists idx_activity_logs_actor_user_id on public.activity_logs(actor_user_id);
