-- HyperRoute Intelligence
-- Customer company subscription tracking.

create table if not exists public.company_subscriptions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  company_id uuid not null references public.companies(id) on delete cascade,
  plan_name text not null default 'professional',
  monthly_price numeric not null default 199,
  billing_status text not null default 'trial',
  trial_ends_at date,
  renews_at date,
  canceled_at date,
  notes text,
  unique (company_id)
);

alter table public.company_subscriptions enable row level security;

drop policy if exists "company_subscriptions_read" on public.company_subscriptions;
drop policy if exists "company_subscriptions_insert" on public.company_subscriptions;
drop policy if exists "company_subscriptions_update" on public.company_subscriptions;
drop policy if exists "company_subscriptions_delete" on public.company_subscriptions;

create policy "company_subscriptions_read"
on public.company_subscriptions
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_subscriptions_insert"
on public.company_subscriptions
for insert
to authenticated
with check (
  public.user_is_platform_admin()
);

create policy "company_subscriptions_update"
on public.company_subscriptions
for update
to authenticated
using (
  public.user_is_platform_admin()
)
with check (
  public.user_is_platform_admin()
);

create policy "company_subscriptions_delete"
on public.company_subscriptions
for delete
to authenticated
using (
  public.user_is_platform_admin()
);

insert into public.company_subscriptions (
  company_id,
  plan_name,
  monthly_price,
  billing_status
)
select
  c.id,
  'professional',
  199,
  'trial'
from public.companies c
where not exists (
  select 1
  from public.company_subscriptions cs
  where cs.company_id = c.id
);

create index if not exists idx_company_subscriptions_company_id
on public.company_subscriptions(company_id);

create index if not exists idx_company_subscriptions_status
on public.company_subscriptions(billing_status);
