-- HyperRoute Intelligence
-- Company admin access, invites, and role policies.
-- Safe to run more than once in Supabase SQL Editor.

create table if not exists public.user_invites (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  company_id uuid not null references public.companies(id) on delete cascade,
  email text not null,
  role text not null default 'dispatcher',
  status text not null default 'pending',
  invited_by uuid default auth.uid(),
  notes text,
  unique (company_id, email)
);

alter table public.user_invites enable row level security;

create index if not exists idx_user_invites_company_id on public.user_invites(company_id);
create index if not exists idx_user_invites_email on public.user_invites(email);
create index if not exists idx_user_invites_status on public.user_invites(status);

create or replace function public.user_is_platform_admin()
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  admin_found boolean := false;
begin
  if auth.uid() is null then
    return false;
  end if;

  if to_regclass('public.platform_admins') is null then
    return false;
  end if;

  execute
    'select exists (
       select 1
       from public.platform_admins
       where user_id = $1
       and status = ''active''
     )'
  into admin_found
  using auth.uid();

  return coalesce(admin_found, false);
end;
$$;

create or replace function public.user_is_company_admin(company_id_input uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.company_users
    where company_id = company_id_input
      and user_id = auth.uid()
      and status = 'active'
      and role in ('owner', 'admin', 'company_owner', 'company_admin')
  )
$$;

create or replace function public.user_is_company_member(company_id_input uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.company_users
    where company_id = company_id_input
      and user_id = auth.uid()
      and status = 'active'
  )
$$;

grant execute on function public.user_is_platform_admin() to authenticated;
grant execute on function public.user_is_company_admin(uuid) to authenticated;
grant execute on function public.user_is_company_member(uuid) to authenticated;

alter table public.companies enable row level security;
alter table public.company_users enable row level security;

drop policy if exists "company_admin_read_companies" on public.companies;
drop policy if exists "company_admin_insert_companies" on public.companies;
drop policy if exists "company_admin_update_companies" on public.companies;
drop policy if exists "allow_read_companies" on public.companies;
drop policy if exists "allow_insert_companies" on public.companies;
drop policy if exists "allow_update_companies" on public.companies;

create policy "company_admin_read_companies"
on public.companies
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(id)
);

create policy "company_admin_insert_companies"
on public.companies
for insert
to authenticated
with check (
  public.user_is_platform_admin()
);

create policy "company_admin_update_companies"
on public.companies
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(id)
);

drop policy if exists "company_admin_read_company_users" on public.company_users;
drop policy if exists "company_admin_insert_company_users" on public.company_users;
drop policy if exists "company_admin_update_company_users" on public.company_users;
drop policy if exists "company_admin_delete_company_users" on public.company_users;
drop policy if exists "allow_read_company_users" on public.company_users;
drop policy if exists "allow_insert_company_users" on public.company_users;
drop policy if exists "allow_update_company_users" on public.company_users;

create policy "company_admin_read_company_users"
on public.company_users
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
  or user_id = auth.uid()
);

create policy "company_admin_insert_company_users"
on public.company_users
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_admin_update_company_users"
on public.company_users
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_admin_delete_company_users"
on public.company_users
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

drop policy if exists "company_admin_read_user_invites" on public.user_invites;
drop policy if exists "company_admin_insert_user_invites" on public.user_invites;
drop policy if exists "company_admin_update_user_invites" on public.user_invites;
drop policy if exists "company_admin_delete_user_invites" on public.user_invites;

create policy "company_admin_read_user_invites"
on public.user_invites
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_admin_insert_user_invites"
on public.user_invites
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_admin_update_user_invites"
on public.user_invites
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_admin_delete_user_invites"
on public.user_invites
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);
