-- HyperRoute Intelligence
-- Company document center and private storage bucket.
-- Safe to run more than once in Supabase SQL Editor.

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  company_id uuid not null references public.companies(id) on delete cascade,
  entity_type text not null default 'general',
  entity_id text,
  document_type text not null default 'other',
  file_name text not null,
  file_path text not null,
  file_size bigint,
  mime_type text,
  notes text,
  uploaded_by uuid default auth.uid()
);

alter table public.documents enable row level security;

create index if not exists idx_documents_company_id on public.documents(company_id);
create index if not exists idx_documents_entity on public.documents(company_id, entity_type, entity_id);
create index if not exists idx_documents_document_type on public.documents(document_type);
create index if not exists idx_documents_created_at on public.documents(created_at desc);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'company-documents',
  'company-documents',
  false,
  52428800,
  array[
    'application/pdf',
    'image/png',
    'image/jpeg',
    'image/webp',
    'text/plain',
    'text/csv',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "documents_company_read" on public.documents;
drop policy if exists "documents_company_insert" on public.documents;
drop policy if exists "documents_company_update" on public.documents;
drop policy if exists "documents_company_delete" on public.documents;

create policy "documents_company_read"
on public.documents
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "documents_company_insert"
on public.documents
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "documents_company_update"
on public.documents
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
  or uploaded_by = auth.uid()
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
  or uploaded_by = auth.uid()
);

create policy "documents_company_delete"
on public.documents
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
  or uploaded_by = auth.uid()
);

drop policy if exists "company_documents_read" on storage.objects;
drop policy if exists "company_documents_insert" on storage.objects;
drop policy if exists "company_documents_update" on storage.objects;
drop policy if exists "company_documents_delete" on storage.objects;

create policy "company_documents_read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'company-documents'
  and (
    public.user_is_platform_admin()
    or public.user_is_company_member(((storage.foldername(name))[1])::uuid)
  )
);

create policy "company_documents_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'company-documents'
  and (
    public.user_is_platform_admin()
    or public.user_is_company_member(((storage.foldername(name))[1])::uuid)
  )
);

create policy "company_documents_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'company-documents'
  and (
    public.user_is_platform_admin()
    or public.user_is_company_admin(((storage.foldername(name))[1])::uuid)
    or owner = auth.uid()
  )
)
with check (
  bucket_id = 'company-documents'
  and (
    public.user_is_platform_admin()
    or public.user_is_company_admin(((storage.foldername(name))[1])::uuid)
    or owner = auth.uid()
  )
);

create policy "company_documents_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'company-documents'
  and (
    public.user_is_platform_admin()
    or public.user_is_company_admin(((storage.foldername(name))[1])::uuid)
    or owner = auth.uid()
  )
);
