-- HyperRoute Intelligence
-- Load lifecycle automation support.
-- Safe to run more than once.

alter table public.loads
add column if not exists company_id uuid references public.companies(id) on delete set null;

create table if not exists public.load_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  company_id uuid references public.companies(id) on delete cascade,
  load_id bigint not null references public.loads(id) on delete cascade,
  event_type text not null,
  event_time timestamp with time zone not null default now(),
  location text,
  notes text
);

alter table public.loads enable row level security;
alter table public.load_events enable row level security;

create index if not exists idx_loads_company_id on public.loads(company_id);
create index if not exists idx_loads_status on public.loads(status);
create index if not exists idx_load_events_company_id on public.load_events(company_id);
create index if not exists idx_load_events_load_id on public.load_events(load_id);
create index if not exists idx_load_events_event_time on public.load_events(event_time desc);

drop policy if exists "loads_company_read" on public.loads;
drop policy if exists "loads_company_insert" on public.loads;
drop policy if exists "loads_company_update" on public.loads;
drop policy if exists "loads_company_delete" on public.loads;

create policy "loads_company_read"
on public.loads
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "loads_company_insert"
on public.loads
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "loads_company_update"
on public.loads
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "loads_company_delete"
on public.loads
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

drop policy if exists "load_events_company_read" on public.load_events;
drop policy if exists "load_events_company_insert" on public.load_events;
drop policy if exists "load_events_company_update" on public.load_events;
drop policy if exists "load_events_company_delete" on public.load_events;

create policy "load_events_company_read"
on public.load_events
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "load_events_company_insert"
on public.load_events
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "load_events_company_update"
on public.load_events
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "load_events_company_delete"
on public.load_events
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);
