-- HyperRoute Intelligence
-- Maintenance scheduling automation.
-- Safe to run more than once in Supabase SQL Editor.

alter table public.maintenance_logs
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.maintenance_logs
add column if not exists cost numeric;

alter table public.maintenance_logs
add column if not exists service_date date;

create table if not exists public.maintenance_schedules (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  company_id uuid not null references public.companies(id) on delete cascade,
  truck_id bigint not null references public.trucks(id) on delete cascade,
  maintenance_type text not null,
  interval_miles integer,
  interval_days integer,
  next_due_mileage integer,
  next_due_date date,
  last_completed_at timestamp with time zone,
  last_maintenance_log_id bigint references public.maintenance_logs(id) on delete set null,
  status text not null default 'active'
);

alter table public.maintenance_logs enable row level security;
alter table public.maintenance_schedules enable row level security;

create index if not exists idx_maintenance_logs_company_id on public.maintenance_logs(company_id);
create index if not exists idx_maintenance_logs_truck_id on public.maintenance_logs(truck_id);
create index if not exists idx_maintenance_schedules_company_id on public.maintenance_schedules(company_id);
create index if not exists idx_maintenance_schedules_truck_id on public.maintenance_schedules(truck_id);
create index if not exists idx_maintenance_schedules_due_date on public.maintenance_schedules(next_due_date);

drop policy if exists "maintenance_logs_company_read" on public.maintenance_logs;
drop policy if exists "maintenance_logs_company_insert" on public.maintenance_logs;
drop policy if exists "maintenance_logs_company_update" on public.maintenance_logs;
drop policy if exists "maintenance_logs_company_delete" on public.maintenance_logs;

create policy "maintenance_logs_company_read"
on public.maintenance_logs
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "maintenance_logs_company_insert"
on public.maintenance_logs
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "maintenance_logs_company_update"
on public.maintenance_logs
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "maintenance_logs_company_delete"
on public.maintenance_logs
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

drop policy if exists "maintenance_schedules_company_read" on public.maintenance_schedules;
drop policy if exists "maintenance_schedules_company_insert" on public.maintenance_schedules;
drop policy if exists "maintenance_schedules_company_update" on public.maintenance_schedules;
drop policy if exists "maintenance_schedules_company_delete" on public.maintenance_schedules;

create policy "maintenance_schedules_company_read"
on public.maintenance_schedules
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "maintenance_schedules_company_insert"
on public.maintenance_schedules
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "maintenance_schedules_company_update"
on public.maintenance_schedules
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
  or public.user_is_company_member(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
  or public.user_is_company_member(company_id)
);

create policy "maintenance_schedules_company_delete"
on public.maintenance_schedules
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);
