-- HyperRoute Intelligence
-- Multi-company SaaS foundation, phase 1.
--
-- This script adds company/account structure without removing your current
-- working public policies. Run this first, confirm the app still works, then
-- update application code and stricter RLS policies in the next phase.

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  company_name text not null,
  legal_name text,
  phone text,
  email text,
  website text,
  address_line_1 text,
  address_line_2 text,
  city text,
  state text,
  zip text,
  mc_number text,
  dot_number text,
  status text not null default 'active'
);

alter table public.companies enable row level security;

drop policy if exists "allow_read_companies" on public.companies;
create policy "allow_read_companies"
on public.companies
for select
to public
using (true);

drop policy if exists "allow_insert_companies" on public.companies;
create policy "allow_insert_companies"
on public.companies
for insert
to public
with check (true);

drop policy if exists "allow_update_companies" on public.companies;
create policy "allow_update_companies"
on public.companies
for update
to public
using (true)
with check (true);

insert into public.companies (
  company_name,
  legal_name,
  status
)
select
  coalesce((select company_name from public.company_settings where id = 1), 'HyperRoute Intelligence'),
  coalesce((select company_name from public.company_settings where id = 1), 'HyperRoute Intelligence'),
  'active'
where not exists (
  select 1 from public.companies
);

create table if not exists public.company_users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid not null,
  role text not null default 'dispatcher',
  status text not null default 'active',
  unique (company_id, user_id)
);

alter table public.company_users enable row level security;

drop policy if exists "allow_read_company_users" on public.company_users;
create policy "allow_read_company_users"
on public.company_users
for select
to public
using (true);

drop policy if exists "allow_insert_company_users" on public.company_users;
create policy "allow_insert_company_users"
on public.company_users
for insert
to public
with check (true);

drop policy if exists "allow_update_company_users" on public.company_users;
create policy "allow_update_company_users"
on public.company_users
for update
to public
using (true)
with check (true);

alter table public.profiles
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.profiles
add column if not exists role text default 'dispatcher';

alter table public.company_settings
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.drivers
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.driver_compliance
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.trucks
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.loads
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.assignments
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.maintenance_logs
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.alerts
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.customers
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.invoices
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.load_events
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.load_documents
add column if not exists company_id uuid references public.companies(id) on delete set null;

alter table public.settlements
add column if not exists company_id uuid references public.companies(id) on delete set null;

do $$
declare
  default_company_id uuid;
begin
  select id into default_company_id
  from public.companies
  order by created_at asc
  limit 1;

  if default_company_id is not null then
    update public.company_settings set company_id = default_company_id where company_id is null;
    update public.drivers set company_id = default_company_id where company_id is null;
    update public.driver_compliance set company_id = default_company_id where company_id is null;
    update public.trucks set company_id = default_company_id where company_id is null;
    update public.loads set company_id = default_company_id where company_id is null;
    update public.assignments set company_id = default_company_id where company_id is null;
    update public.maintenance_logs set company_id = default_company_id where company_id is null;
    update public.alerts set company_id = default_company_id where company_id is null;
    update public.customers set company_id = default_company_id where company_id is null;
    update public.invoices set company_id = default_company_id where company_id is null;
    update public.load_events set company_id = default_company_id where company_id is null;
    update public.load_documents set company_id = default_company_id where company_id is null;
    update public.settlements set company_id = default_company_id where company_id is null;
    update public.profiles set company_id = default_company_id where company_id is null;
  end if;
end $$;

create index if not exists idx_profiles_company_id on public.profiles(company_id);
create index if not exists idx_company_settings_company_id on public.company_settings(company_id);
create index if not exists idx_drivers_company_id on public.drivers(company_id);
create index if not exists idx_driver_compliance_company_id on public.driver_compliance(company_id);
create index if not exists idx_trucks_company_id on public.trucks(company_id);
create index if not exists idx_loads_company_id on public.loads(company_id);
create index if not exists idx_assignments_company_id on public.assignments(company_id);
create index if not exists idx_maintenance_logs_company_id on public.maintenance_logs(company_id);
create index if not exists idx_alerts_company_id on public.alerts(company_id);
create index if not exists idx_customers_company_id on public.customers(company_id);
create index if not exists idx_invoices_company_id on public.invoices(company_id);
create index if not exists idx_load_events_company_id on public.load_events(company_id);
create index if not exists idx_load_documents_company_id on public.load_documents(company_id);
create index if not exists idx_settlements_company_id on public.settlements(company_id);

create or replace function public.current_user_company_id()
returns uuid
language sql
stable
as $$
  select company_id
  from public.profiles
  where id = auth.uid()
  limit 1
$$;
