-- HyperRoute Intelligence
-- Platform user invite queue.
--
-- This lets platform admins invite users by email without exposing a Supabase
-- service-role key in the browser. Create the Auth user separately, then attach
-- the Auth user ID to company_users when the account exists.

create table if not exists public.user_invites (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  company_id uuid not null references public.companies(id) on delete cascade,
  email text not null,
  role text not null default 'dispatcher',
  status text not null default 'pending',
  invited_by uuid,
  notes text,
  unique (company_id, email)
);

alter table public.user_invites enable row level security;

drop policy if exists "user_invites_platform_read" on public.user_invites;
drop policy if exists "user_invites_platform_insert" on public.user_invites;
drop policy if exists "user_invites_platform_update" on public.user_invites;
drop policy if exists "user_invites_platform_delete" on public.user_invites;

create policy "user_invites_platform_read"
on public.user_invites
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "user_invites_platform_insert"
on public.user_invites
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "user_invites_platform_update"
on public.user_invites
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "user_invites_platform_delete"
on public.user_invites
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create index if not exists idx_user_invites_company_id on public.user_invites(company_id);
create index if not exists idx_user_invites_email on public.user_invites(email);
create index if not exists idx_user_invites_status on public.user_invites(status);
