-- HyperRoute Intelligence
-- Quotes module: quote-to-load workflow.
-- Safe to run more than once.

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  company_id uuid not null references public.companies(id) on delete cascade,
  quote_number text,
  customer_name text,
  pickup_location text,
  delivery_location text,
  pickup_date date,
  delivery_date date,
  equipment_type text,
  commodity text,
  weight integer,
  estimated_miles integer,
  quoted_rate numeric,
  status text not null default 'draft',
  expiration_date date,
  notes text,
  load_id bigint references public.loads(id) on delete set null,
  converted_at timestamp with time zone
);

alter table public.quotes enable row level security;

create index if not exists idx_quotes_company_id on public.quotes(company_id);
create index if not exists idx_quotes_status on public.quotes(status);
create index if not exists idx_quotes_created_at on public.quotes(created_at desc);
create unique index if not exists idx_quotes_company_quote_number_unique
on public.quotes(company_id, quote_number)
where quote_number is not null;

drop policy if exists "quotes_company_read" on public.quotes;
drop policy if exists "quotes_company_insert" on public.quotes;
drop policy if exists "quotes_company_update" on public.quotes;
drop policy if exists "quotes_company_delete" on public.quotes;

create policy "quotes_company_read"
on public.quotes
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "quotes_company_insert"
on public.quotes
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "quotes_company_update"
on public.quotes
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_member(company_id)
);

create policy "quotes_company_delete"
on public.quotes
for delete
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);
