create table if not exists public.settlements (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  settlement_date date,
  load_id bigint references public.loads(id) on delete set null,
  driver_id bigint references public.drivers(id) on delete set null,
  settlement_number text,
  status text not null default 'draft',
  gross_revenue numeric not null default 0,
  driver_pay numeric not null default 0,
  deductions numeric not null default 0,
  net_profit numeric not null default 0,
  notes text
);

alter table public.settlements enable row level security;

drop policy if exists "allow_read_settlements" on public.settlements;
create policy "allow_read_settlements"
on public.settlements
for select
to public
using (true);

drop policy if exists "allow_insert_settlements" on public.settlements;
create policy "allow_insert_settlements"
on public.settlements
for insert
to public
with check (true);

drop policy if exists "allow_update_settlements" on public.settlements;
create policy "allow_update_settlements"
on public.settlements
for update
to public
using (true)
with check (true);

drop policy if exists "allow_delete_settlements" on public.settlements;
create policy "allow_delete_settlements"
on public.settlements
for delete
to public
using (true);
