-- HyperRoute Intelligence
-- Subscription plans and company subscription management.
-- Safe to run more than once.

create table if not exists public.company_subscriptions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  company_id uuid not null references public.companies(id) on delete cascade,
  plan_name text not null default 'professional',
  monthly_price numeric not null default 199,
  billing_status text not null default 'trial',
  trial_ends_at date,
  renews_at date,
  canceled_at date,
  notes text,
  unique (company_id)
);

alter table public.company_subscriptions
add column if not exists stripe_customer_id text;

alter table public.company_subscriptions
add column if not exists stripe_subscription_id text;

alter table public.company_subscriptions
add column if not exists feature_limits jsonb not null default '{}'::jsonb;

alter table public.company_subscriptions
alter column plan_name set default 'professional';

alter table public.company_subscriptions
alter column monthly_price set default 199;

alter table public.company_subscriptions enable row level security;

create index if not exists idx_company_subscriptions_company_id
on public.company_subscriptions(company_id);

create index if not exists idx_company_subscriptions_status
on public.company_subscriptions(billing_status);

create index if not exists idx_company_subscriptions_plan
on public.company_subscriptions(plan_name);

insert into public.company_subscriptions (
  company_id,
  plan_name,
  monthly_price,
  billing_status,
  trial_ends_at,
  renews_at,
  feature_limits
)
select
  c.id,
  'professional',
  199,
  'trial',
  current_date + 14,
  current_date + 14,
  '{"drivers":50,"trucks":50,"loads":500,"documents":1500,"users":10}'::jsonb
from public.companies c
where not exists (
  select 1
  from public.company_subscriptions cs
  where cs.company_id = c.id
);

update public.company_subscriptions
set
  monthly_price = case plan_name
    when 'starter' then 99
    when 'professional' then 199
    when 'business' then 399
    when 'enterprise' then 0
    else monthly_price
  end,
  feature_limits = case plan_name
    when 'starter' then '{"drivers":10,"trucks":10,"loads":100,"documents":250,"users":3}'::jsonb
    when 'professional' then '{"drivers":50,"trucks":50,"loads":500,"documents":1500,"users":10}'::jsonb
    when 'business' then '{"drivers":200,"trucks":200,"loads":2500,"documents":8000,"users":35}'::jsonb
    when 'enterprise' then '{"drivers":null,"trucks":null,"loads":null,"documents":null,"users":null}'::jsonb
    else feature_limits
  end,
  updated_at = now();

drop policy if exists "company_subscriptions_read" on public.company_subscriptions;
drop policy if exists "company_subscriptions_insert" on public.company_subscriptions;
drop policy if exists "company_subscriptions_update" on public.company_subscriptions;
drop policy if exists "company_subscriptions_delete" on public.company_subscriptions;

create policy "company_subscriptions_read"
on public.company_subscriptions
for select
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_subscriptions_insert"
on public.company_subscriptions
for insert
to authenticated
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_subscriptions_update"
on public.company_subscriptions
for update
to authenticated
using (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
)
with check (
  public.user_is_platform_admin()
  or public.user_is_company_admin(company_id)
);

create policy "company_subscriptions_delete"
on public.company_subscriptions
for delete
to authenticated
using (
  public.user_is_platform_admin()
);
